# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from . import transmitter_pb2 as transmitter__pb2


class TransmitterStub(object):
    """The message interface exported by the server
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendMessage = channel.unary_unary(
                '/Transmitter/SendMessage',
                request_serializer=transmitter__pb2.Message.SerializeToString,
                response_deserializer=transmitter__pb2.Result.FromString,
                )


class TransmitterServicer(object):
    """The message interface exported by the server
    """

    def SendMessage(self, request, context):
        """Sends a message via Line.

        Can be a text message or an image message or both.

        The result return is the return status of the operation. 
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TransmitterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendMessage': grpc.unary_unary_rpc_method_handler(
                    servicer.SendMessage,
                    request_deserializer=transmitter__pb2.Message.FromString,
                    response_serializer=transmitter__pb2.Result.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Transmitter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Transmitter(object):
    """The message interface exported by the server
    """

    @staticmethod
    def SendMessage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Transmitter/SendMessage',
            transmitter__pb2.Message.SerializeToString,
            transmitter__pb2.Result.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
