# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transmitter.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import wrappers_pb2 as google_dot_protobuf_dot_wrappers__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11transmitter.proto\x1a\x1egoogle/protobuf/wrappers.proto\"3\n\x06Images\x12\x0c\n\x04path\x18\x01 \x01(\t\x12\x0c\n\x04sort\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\"\x16\n\x06Source\x12\x0c\n\x04name\x18\x01 \x01(\t\"\x83\x01\n\x07Message\x12\x17\n\x06source\x18\x01 \x01(\x0b\x32\x07.Source\x12\x1a\n\x04type\x18\x02 \x01(\x0e\x32\x0c.MessageType\x12*\n\x04text\x18\x03 \x01(\x0b\x32\x1c.google.protobuf.StringValue\x12\x17\n\x06images\x18\x04 \x03(\x0b\x32\x07.Images\"\'\n\x06Result\x12\x0c\n\x04\x63ode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t*,\n\x0bMessageType\x12\x08\n\x04TEXT\x10\x00\x12\t\n\x05IMAGE\x10\x01\x12\x08\n\x04\x42OTH\x10\x02\x32\x31\n\x0bTransmitter\x12\"\n\x0bSendMessage\x12\x08.Message\x1a\x07.Result\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transmitter_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MESSAGETYPE']._serialized_start=305
  _globals['_MESSAGETYPE']._serialized_end=349
  _globals['_IMAGES']._serialized_start=53
  _globals['_IMAGES']._serialized_end=104
  _globals['_SOURCE']._serialized_start=106
  _globals['_SOURCE']._serialized_end=128
  _globals['_MESSAGE']._serialized_start=131
  _globals['_MESSAGE']._serialized_end=262
  _globals['_RESULT']._serialized_start=264
  _globals['_RESULT']._serialized_end=303
  _globals['_TRANSMITTER']._serialized_start=351
  _globals['_TRANSMITTER']._serialized_end=400
# @@protoc_insertion_point(module_scope)
